
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadorFlexCup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 24;
  public static final int MENQUE = 17;
  public static final int POT = 15;
  public static final int RTRUE = 44;
  public static final int POR = 13;
  public static final int RWHILE = 28;
  public static final int IGUALACION = 48;
  public static final int RCONTINUE = 42;
  public static final int RNULL = 36;
  public static final int RDEFAULT = 43;
  public static final int DOSPT = 9;
  public static final int TERNARIO = 47;
  public static final int RFALSE = 45;
  public static final int LLAVIZQ = 5;
  public static final int RELSE = 30;
  public static final int RFUNC = 41;
  public static final int IDENTIFICADOR = 49;
  public static final int NOT = 23;
  public static final int AND = 22;
  public static final int IGUAL = 46;
  public static final int CORDER = 8;
  public static final int IGUALFUNC = 33;
  public static final int OR = 21;
  public static final int DIV = 14;
  public static final int MAYIGUAL = 20;
  public static final int UMENOS = 27;
  public static final int RDO = 32;
  public static final int EOF = 0;
  public static final int PARIZQ = 3;
  public static final int DECIMAL = 25;
  public static final int error = 1;
  public static final int COMA = 10;
  public static final int CADENA = 26;
  public static final int MENOS = 12;
  public static final int MOD = 16;
  public static final int DIFERENCIACION = 34;
  public static final int MAYQUE = 18;
  public static final int LLAVDER = 6;
  public static final int RRETURN = 40;
  public static final int RCASE = 37;
  public static final int MENIGUAL = 19;
  public static final int PTCOMA = 2;
  public static final int RSWITCH = 39;
  public static final int RIN = 31;
  public static final int RFOR = 35;
  public static final int PARDER = 4;
  public static final int CORIZQ = 7;
  public static final int RBREAK = 38;
  public static final int RIF = 29;
  public static final int MAS = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "LLAVIZQ",
  "LLAVDER",
  "CORIZQ",
  "CORDER",
  "DOSPT",
  "COMA",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "POT",
  "MOD",
  "MENQUE",
  "MAYQUE",
  "MENIGUAL",
  "MAYIGUAL",
  "OR",
  "AND",
  "NOT",
  "NUMERO",
  "DECIMAL",
  "CADENA",
  "UMENOS",
  "RWHILE",
  "RIF",
  "RELSE",
  "RIN",
  "RDO",
  "IGUALFUNC",
  "DIFERENCIACION",
  "RFOR",
  "RNULL",
  "RCASE",
  "RBREAK",
  "RSWITCH",
  "RRETURN",
  "RFUNC",
  "RCONTINUE",
  "RDEFAULT",
  "RTRUE",
  "RFALSE",
  "IGUAL",
  "TERNARIO",
  "IGUALACION",
  "IDENTIFICADOR"
  };
}

