
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadorFlexCup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 24;
  public static final int MENQUE = 17;
  public static final int RBARPLOT = 60;
  public static final int RIMPRIMIR = 28;
  public static final int POT = 15;
  public static final int POR = 13;
  public static final int RWHILE = 29;
  public static final int IGUALACION = 68;
  public static final int RMODE = 47;
  public static final int RSTRLENGTH = 65;
  public static final int RCONTINUE = 62;
  public static final int RNULL = 39;
  public static final int RMEAN = 46;
  public static final int RLENGTH = 53;
  public static final int DOSPT = 9;
  public static final int TERNARIO = 67;
  public static final int RNCOL = 41;
  public static final int LLAVIZQ = 5;
  public static final int RELSE = 31;
  public static final int RFUNC = 61;
  public static final int IDENTIFICADOR = 69;
  public static final int RROUND = 49;
  public static final int RPRINT = 48;
  public static final int NOT = 23;
  public static final int AND = 22;
  public static final int IGUAL = 66;
  public static final int RREMOVE = 56;
  public static final int RTOUPPER = 64;
  public static final int RLIST = 42;
  public static final int CORDER = 8;
  public static final int IGUALFUNC = 35;
  public static final int OR = 21;
  public static final int RMATRIX = 59;
  public static final int RNROW = 40;
  public static final int DIV = 14;
  public static final int MAYIGUAL = 20;
  public static final int UMENOS = 27;
  public static final int RMEDIAN = 58;
  public static final int RDO = 34;
  public static final int EOF = 0;
  public static final int PARIZQ = 3;
  public static final int DECIMAL = 25;
  public static final int error = 1;
  public static final int RC = 32;
  public static final int RTYPEOF = 57;
  public static final int COMA = 10;
  public static final int RARRAY = 51;
  public static final int CADENA = 26;
  public static final int MENOS = 12;
  public static final int RTOLOWER = 63;
  public static final int MOD = 16;
  public static final int DIFERENCIACION = 36;
  public static final int MAYQUE = 18;
  public static final int LLAVDER = 6;
  public static final int RHIST = 45;
  public static final int RRETURN = 55;
  public static final int RCASE = 44;
  public static final int MENIGUAL = 19;
  public static final int RPIE = 38;
  public static final int PTCOMA = 2;
  public static final int RSWITCH = 54;
  public static final int RIN = 33;
  public static final int RTRUNK = 50;
  public static final int RFOR = 37;
  public static final int PARDER = 4;
  public static final int CORIZQ = 7;
  public static final int RBREAK = 52;
  public static final int RPLOT = 43;
  public static final int RIF = 30;
  public static final int MAS = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "LLAVIZQ",
  "LLAVDER",
  "CORIZQ",
  "CORDER",
  "DOSPT",
  "COMA",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "POT",
  "MOD",
  "MENQUE",
  "MAYQUE",
  "MENIGUAL",
  "MAYIGUAL",
  "OR",
  "AND",
  "NOT",
  "NUMERO",
  "DECIMAL",
  "CADENA",
  "UMENOS",
  "RIMPRIMIR",
  "RWHILE",
  "RIF",
  "RELSE",
  "RC",
  "RIN",
  "RDO",
  "IGUALFUNC",
  "DIFERENCIACION",
  "RFOR",
  "RPIE",
  "RNULL",
  "RNROW",
  "RNCOL",
  "RLIST",
  "RPLOT",
  "RCASE",
  "RHIST",
  "RMEAN",
  "RMODE",
  "RPRINT",
  "RROUND",
  "RTRUNK",
  "RARRAY",
  "RBREAK",
  "RLENGTH",
  "RSWITCH",
  "RRETURN",
  "RREMOVE",
  "RTYPEOF",
  "RMEDIAN",
  "RMATRIX",
  "RBARPLOT",
  "RFUNC",
  "RCONTINUE",
  "RTOLOWER",
  "RTOUPPER",
  "RSTRLENGTH",
  "IGUAL",
  "TERNARIO",
  "IGUALACION",
  "IDENTIFICADOR"
  };
}

